[build.environment]
  NODE_VERSION = "18.18.0"

[build]
  command = "CI= npm run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
