[build.environment]
  NODE_VERSION = "18.18.0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
